### ISSUE TITLE
how do I setup the transparency??

### ISSUE THREAD

**Issue by josuevalrob** [rogeraabbccdd/vscode-dark-red#1]
What should I do If i want to increase the transparency??

**Comment by rogeraabbccdd** [comment]
Hi, sorry for late reply.
You can add this in your `settings.json` if you're using [my custom vscode build](https://github.com/rogeraabbccdd/vscode).
```json
"workbench.colorCustomizations": {
    "workbench.background": "#ff0000d0"
}
```
